### PR TITLE
(for discussion) uWSGI + Plack support

### PR DESCRIPTION
**Pull request by mbarbon**
Hi,
first of all, I'm very excited about remote debugging support in the Perl/IDEA plugin, thanks for working on it!

The specific use case I have at work is debugging various large Plack applications running under uWSGI (with pre-forking). What I have for other editors/IDEs (using https://github.com/mbarbon/perl-remote-debugging-client and https://github.com/mbarbon/plack-middleware-dbgp) is:
- during application startup debugging is disabled by default; $^P is setup in a way so that the code is prepared for debugging but DB::DB and  DB::sub are not called (so the overhead is close to 0)
- at request start the uWSGI child process serving the request tries to connect to the IDE; if it fails, debugging is kept disabled (again, with close to 0 overhead)
- if the connection is successful, debugging is enabled
- at request end, the uWSGI child disconnects from the IDE and disables debugging

I'd like to replicate the same setup with IDEA, and I have a tentative set of changes in this pull request (I only tested this on a trivial test application, so I might need some tweaks once I test it at work). Example usage is at https://github.com/mbarbon/plack-middleware-camelcadedb/blob/master/lib/Plack/Middleware/Camelcadedb.pm#L116
- if $ENV{PERL5_DEBUG_AUTOSTART} is explicitly set to 0, no connection attempt is performed during application startup
- adds connect(), disconnect(), is_connected(), connect_or_reconnect() for explicit connection management
- adds disable() to disable calls to DB::DB and DB::sub, and a matching enable()

Not in this PR, and wishlist, I'd like to add an option to connect over an Unix domain socket (I will need to use connection forwarding anyway, and using an Unix domain avoids the need for an open port on the application host which communicates directly with the IDE). I'd like to have this because the development environment is semi-shared, but it's not critical.

Let me know if this set of changes is something you're interested in incorporating, and if there is anything you would prefer to be done a different way (I will document the changes in the final PR).

Thanks!
Mattia

### CODE REVIEW

**Comment by mbarbon** [comment]
I was able to test this with one of our applications.

It seems to be working correctly except for a speed issue related to the number of Perl files loaded by the application: after the debugger hits the first breakpoint, it sends a large LOADED_FILES_DELTA event to IDEA; the event contains ~60k added items (~5k files and ~55k evals). After that I see IDEA using CPU for almost two minutes [1]; and then debugging works fine.

I had a quick look at the plugin, and it it should be relatively simple to fix [2]. I will finish this pull request first and then have a stab at reducing reducing CPU usage for large LOADED_FILES_DELTA events.

Cheers,
Mattia

[1] the first time around I was too impatient and gave up after ~30 seconds
[2] but I know nothing about Swing, so maybe I'm being overly optimistic

**Comment by mbarbon** [comment]
I pushed an updated version of the branch; it's pretty much the same code as the oroginal PR, with some print()s removed and some comments added.

I added some POD documenting enable/disable/connect/disconnect/is_connected (because they form a sort of "API"); feel free to leave it out if you don't want it advertised or you don't think it is relevant.

**Comment by akjohnston** [comment]
Could someone please provide some details of how to set up Apache and IntelliJ to get this working? 

If someone can provide some information to get me started I am very happy to write this up formally as a Wiki page so that others can get started more quickly.

I think I need to know how to set up the environment, what to put in the Apache conf file, and the debug config for IntelliJ.

Thanks
Andrew

**Comment by simonschaufi** [comment]
@mbarbon I can only repeat the message from @akjohnston: Please provide a step by step tutorial how to configure IntelliJ and Apache/Nginx on how to setup browser debugging. Thank you!

**Comment by simonschaufi** [comment]
@akjohnston I got it working with nginx. Maybe it is similar with apache, I don't know. See my documentation here: https://github.com/Camelcade/Perl5-IDEA/issues/2127#issuecomment-564773031

**Pull request merged**
